FROM jenkins/jenkins:lts

USER root

# Docker CLI + basics
RUN apt-get update && apt-get install -y \
    docker.io curl apt-transport-https lsb-release gnupg \
    && rm -rf /var/lib/apt/lists/*

# Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN groupadd -f docker && usermod -aG docker jenkins

USER jenkins